export const frasiMotivazionali: string[] = [
  "Vai al tuo ritmo, ogni passo conta.",
  "Sei qui, e questo è già straordinario.",
  "Il tuo corpo ti ringrazia per ogni movimento.",
  "Respira, sorridi, continua.",
  "Ogni piccolo progresso è una vittoria reale.",
  "Stai facendo qualcosa di bello per te stesso.",
  "Il movimento è un regalo che fai al tuo corpo.",
  "Anche oggi hai scelto di muoverti. Bravissimo.",
  "Non serve correre, serve andare avanti.",
  "Sii gentile con te stesso mentre ti alleni.",
  "La costanza supera sempre l'intensità.",
  "Un passo dopo l'altro, ce la fai.",
  "Senti quanto sei vivo in questo momento.",
  "Il meglio di te emerge quando ti muovi.",
  "Ogni respiro ti avvicina alla versione migliore.",
  "Non confrontarti con gli altri, solo con ieri.",
  "Stai costruendo qualcosa di duraturo.",
  "Il corpo impara, anche quando la mente dubita.",
  "Prenditi cura di te, ti meriti questo.",
  "Ogni sessione è un seme che stai piantando.",
  "La regolarità è la tua arma più potente.",
  "Non servono grandi gesti, serve presenza.",
  "Sei più forte di quanto credi, davvero.",
  "L'importante è che tu stia provando.",
  "Ogni volta che torni, diventi più solido.",
  "Il tuo impegno parla da solo.",
  "Sii fiero di essere qui.",
  "Ascolta il tuo corpo, ti sta dicendo che ce la fai.",
  "La fatica è passeggera, la forza rimane.",
  "Stai investendo nel tuo benessere.",
  "Oggi conti su di te, e hai ragione.",
  "Il cambiamento si costruisce giorno per giorno.",
  "Siediti nella fatica e poi riparti.",
  "Ogni goccia di sudore racconta la tua storia.",
  "Sii curioso del tuo limite, non spaventato.",
  "Tutto quello che fai oggi conta domani.",
  "Il corpo ricorda ogni sforzo che fai.",
  "Non mollare l'impegno che hai preso con te stesso.",
  "Stai crescendo anche quando non lo senti.",
  "Fai del tuo meglio, oggi è sufficiente.",
  "La tua dedizione è ammirevole.",
  "Ogni round è un capitolo della tua storia.",
  "Muoviti con intenzione e tutto si semplifica.",
  "Stai regalando salute al tuo futuro.",
  "Il corpo si adatta, la mente si rafforza.",
  "Non smettere mai di sorprenderti.",
  "Vai avanti con grazia, non con violenza.",
  "La vera forza è la continuità.",
  "Ti stai allenando per vivere meglio, ricordalo.",
  "Il tuo impegno oggi è il tuo dono di domani.",
  "Ogni momento di fatica ti insegna qualcosa.",
  "Fidati del processo, funziona.",
  "Stai coltivando una versione migliore di te.",
  "Il benessere non ha scorciatoie, ma ne vale la pena.",
  "Sii presente in ogni rep.",
  "Il tuo corpo è la tua casa, trattala bene.",
  "Muoviti con amore per te stesso.",
  "Ogni allenamento è un atto di cura verso di te.",
  "Non esistono giornate sprecate se ti sei mosso.",
  "Stai costruendo fondamenta solide.",
  "La disciplina è la forma più alta di rispetto verso sé stessi.",
  "Vai a testa alta, ce la stai facendo.",
  "Ogni respiro è un nuovo inizio.",
  "Il corpo che alleni oggi è quello che ti porterà lontano.",
  "Non correre verso la fine, goditi il percorso.",
  "Stai diventando più capace ad ogni sessione.",
  "La tua resilienza cresce con ogni sforzo.",
  "Sii orgoglioso di ogni singola rep.",
  "Non c'è allenamento sbagliato se fatto con cuore.",
  "Il ritmo giusto è quello che puoi sostenere.",
  "Abbraccia la fatica, ti sta modellando.",
  "Ogni giorno che ti alleni è un giorno vinto.",
  "Il tuo corpo sa cosa fare, lascialo lavorare.",
  "Stai scrivendo una storia di disciplina e amore.",
  "La costanza è il segreto che nessuno racconta abbastanza.",
  "Fai spazio alla forza dentro di te.",
  "Ogni sessione, anche quella difficile, vale.",
  "Sei sulla strada giusta, non uscirne.",
  "Il coraggio di iniziare è già metà dell'opera.",
  "Stai dimostrando a te stesso di cosa sei capace.",
  "Il sudore è il linguaggio del tuo impegno.",
  "Non giudicare la sessione, vivi la sessione.",
  "Porta rispetto al tuo corpo mentre lo sfidi.",
  "Oggi ti stai prendendo cura di ciò che conta.",
  "Ogni momento di fatica è un momento di crescita.",
  "Il tuo futuro ti ringrazia per questo.",
  "Continua, perché ne vale sempre la pena.",
  "Stai diventando la persona che volevi essere.",
  "Il corpo cresce nei momenti di sfida gentile.",
  "Ogni movimento è un atto di fiducia verso te stesso.",
  "Sii la versione di te di cui sei più orgoglioso.",
  "La forza si accumula in silenzio.",
  "Stai lavorando su qualcosa di duraturo.",
  "Non c'è fretta: ogni progresso è permanente.",
  "Il meglio deve ancora venire.",
  "La tua energia è contagiosa, anche per te.",
  "Stai facendo esattamente quello che serve.",
  "Ogni rep è una piccola promessa mantenuta.",
  "Il tuo corpo risponde all'amore che gli dai.",
  "Continua a sceglierti ogni giorno.",
  "La mente si quieta quando il corpo si muove.",
  "Stai costruendo un equilibrio che dura.",
  "Il movimento libera, anche la mente.",
  "Ogni sessione ti avvicina alla tua versione migliore.",
  "Respira profondamente: sei esattamente dove devi essere.",
  "Stai onorando il tuo impegno verso te stesso.",
  "Piccoli passi, grande destinazione.",
  "Il tuo corpo merita questa attenzione.",
  "Ogni giorno di allenamento è una vittoria silenziosa.",
  "Stai costruendo salute, non solo muscoli.",
  "La tua presenza qui è il gesto più importante.",
  "Ogni sessione è una scelta di cui essere fieri.",
  "Il benessere fisico nutre anche quello mentale.",
  "Stai imparando a conoscerti davvero.",
  "Non serve fare di più, serve fare bene.",
  "Ogni rep ti insegna qualcosa su te stesso.",
  "La fatica passa, ma l'abitudine costruita resta.",
  "Stai diventando più forte ogni settimana.",
  "Il corpo si fida di te perché tu ti fidi di lui.",
  "Ogni giornata di impegno vale doppio.",
  "Non esiste uno sforzo troppo piccolo.",
  "Il movimento è medicina, dosi giornaliere.",
  "Continua: il risultato si vede dall'interno prima che dall'esterno.",
  "Ogni allenamento è un mattone della tua casa.",
  "Sii gentile, sii costante, sii presente.",
  "La tua tenacia ti porterà dove vuoi arrivare.",
  "Il corpo ti segue quando la mente guida con cura.",
  "Stai seminando oggi per raccogliere domani.",
  "La forza non è rumorosa, è silenziosa e solida.",
  "Stai scegliendo la salute ogni volta che vieni qui.",
  "Il tuo corpo ti appartiene, prendine cura.",
  "Non serve essere perfetti, serve essere presenti.",
  "La tua costanza è la tua superpotenza.",
  "Ogni rep è una conversazione tra te e il tuo corpo.",
  "Stai costruendo una relazione sana con il movimento.",
  "Il cammino verso la salute è fatto di piccoli passi.",
  "Ogni sessione ti rende più consapevole di te.",
  "La cura verso sé stessi è la forma più alta d'amore.",
  "Il movimento ti fa sentire vivo, sfruttalo.",
  "Ogni allenamento è una celebrazione di ciò che puoi fare.",
  "La sfida gentile è quella che porta i risultati duraturi.",
  "Stai regalando anni di qualità alla tua vita.",
  "Il tuo impegno è visibile, anche se non lo senti ancora.",
  "Ogni sessione è un investimento ad alto rendimento.",
  "Stai scrivendo la tua storia di benessere.",
  "La pazienza è parte dell'allenamento.",
  "Ogni rep ben fatta vale cento fatte di fretta.",
  "Stai costruendo fiducia in te stesso, rep dopo rep.",
  "Il corpo ricorda ogni sforzo sincero.",
  "Stai trasformando l'abitudine in carattere.",
  "La tua energia positiva muove anche il corpo.",
  "Ogni sessione aggiunge un tassello al mosaico della tua salute.",
  "Stai imparando a stare nella fatica con serenità.",
  "Il corpo si apre quando la mente si rilassa.",
  "Ogni respiro profondo è un atto di cura.",
  "Stai allenando anche la mente, non solo i muscoli.",
  "La tua perseveranza è ammirevole.",
  "Ogni giorno che scegli il movimento, scegli te stesso.",
  "Non serve la perfezione, serve l'intenzione.",
  "Stai costruendo un patrimonio di salute.",
  "Il movimento quotidiano è la migliore medicina preventiva.",
  "Ogni rep fatta con cura vale oro.",
  "Stai diventando qualcuno su cui puoi contare.",
  "La tua forza interiore emerge quando il corpo fatica.",
  "Ogni sessione è un dialogo tra chi eri e chi diventi.",
  "Il corpo fiorisce con attenzione e movimento.",
  "Ogni allenamento è un atto d'amore verso te stesso.",
  "Stai costruendo resistenza, dentro e fuori.",
  "La tua dedizione merita rispetto.",
  "Ogni momento di sforzo è un momento di cura.",
  "Stai imparando che puoi più di quanto pensavi.",
  "Il ritmo che trovi oggi diventa il ritmo della tua vita.",
  "Ogni volta che torni, dimostri di credere in te.",
  "La forza vera è tranquilla e tenace.",
  "Stai aggiungendo vita ai tuoi anni.",
  "Ogni rep è un segnale che mandi al tuo corpo: ce la faccio.",
  "Stai costruendo un'abitudine che cambierà tutto.",
  "Non devi essere veloce, devi essere continuo.",
  "Ogni sessione è un punto fisso in una giornata che cambia.",
  "La fatica oggi è leggerezza domani.",
  "Ogni respiro è un richiamo alla presenza.",
  "Il corpo ti segue, sempre.",
  "Ogni rep aggiunge solidità alla tua struttura.",
  "Stai costruendo una versione di te che dura nel tempo.",
  "La perseveranza calma è la più potente.",
  "Ogni sessione è un capitolo nella storia della tua salute.",
  "Stai imparando a sentirti a casa nel tuo corpo.",
  "Il movimento ti restituisce sempre qualcosa.",
  "Ogni sforzo ha un eco nel futuro.",
  "Stai costruendo un corpo che ti sorprenderà.",
  "La continuità fa miracoli che l'intensità non può fare.",
  "Ogni giorno che torni qui è un giorno guadagnato.",
  "Stai insegnando al tuo corpo cosa significa impegno.",
  "Il progresso ha il suo tempo, rispettalo.",
  "Ogni rep è un passo verso la versione di te che ammiri.",
  "Stai costruendo una storia personale di forza.",
  "La fatica è il tuo compagno di viaggio, non il tuo nemico.",
  "Ogni sessione rinforza non solo i muscoli ma la volontà.",
  "Stai imparando che il corpo è capace di molto.",
  "La calma mentre ci si allena è una forma di potere.",
  "Ogni respiro ti radica nel presente.",
  "Stai portando cura e attenzione a ciò che conta.",
  "Il corpo ti parla, impara ad ascoltarlo.",
  "Ogni rep è un messaggio di fiducia a te stesso.",
  "Stai coltivando la salute come si coltiva un giardino.",
  "La regolarità è il fertilizzante dei tuoi progressi.",
  "Ogni sessione rafforza il patto con te stesso.",
  "Stai costruendo qualcosa di reale, un giorno alla volta.",
  "Il corpo si adatta sempre, dagli tempo.",
  "Stai crescendo verso la luce come una pianta.",
  "La tua forza è una risorsa rinnovabile.",
  "Ogni rep porta più energia di quanta ne consumi.",
  "Stai imparando a trovare pace nel movimento.",
  "Il corpo gioisce quando si muove con intenzione.",
  "Ogni sessione è una piccola celebrazione della vita.",
  "Stai costruendo un sistema di benessere personale.",
  "La salute si guadagna con gesti quotidiani, non eroici.",
  "Ogni rep ti avvicina a una vita più leggera.",
  "Stai facendo la cosa giusta per te.",
  "Il corpo risponde sempre alla cura che gli dedichi.",
  "Ogni giorno di movimento è un giorno pieno.",
  "Stai diventando l'esperto di te stesso.",
  "La fatica è il modo del corpo di ringraziarti.",
  "Ogni sessione semplifica la vita fuori dalla palestra.",
  "Stai costruendo la capacità di affrontare tutto con più energia.",
  "Il movimento quotidiano è il fondamento di tutto il resto.",
  "Ogni rep è un investimento nel tuo domani.",
  "Stai imparando che la perseveranza è più bella della perfezione.",
  "La coerenza costruisce il carattere.",
  "Ogni sessione è un atto di rispetto verso te stesso.",
  "Stai regalando al tuo corpo l'attenzione che merita.",
  "Il benessere è un viaggio quotidiano, non una destinazione.",
  "Ogni rep rafforza non solo il corpo ma anche l'autostima.",
  "Stai costruendo una routine che ti supporta.",
  "La tua presenza qui è già un successo.",
  "Ogni sessione è un 'sì' detto a te stesso.",
  "Stai imparando a trovare energia nello sforzo.",
  "Il corpo conosce la strada, fidati di lui.",
  "Ogni rep è un 'grazie' che dai al tuo corpo.",
  "Stai costruendo abitudini che cambieranno la tua vita.",
  "La cura verso sé stessi inizia qui, con ogni movimento.",
  "Ogni sessione è un capitolo del tuo benessere.",
  "Stai imparando che sei più capace di quanto immaginavi.",
  "Il movimento trasforma l'energia bloccata in forza.",
  "Ogni rep è un passo nella direzione giusta.",
  "Stai costruendo un corpo che ti supporta nei tuoi sogni.",
  "Ogni sessione aggiunge valore alla tua vita.",
  "Stai imparando a fidarti del processo.",
  "Il corpo si rivela in tutta la sua forza con la pratica costante.",
  "Ogni rep è la tua firma su un impegno personale.",
  "Stai costruendo resistenza fisica e mentale insieme.",
  "La tua energia crescerà ad ogni allenamento.",
  "Ogni sessione è un passo verso la libertà fisica.",
  "Stai imparando che il corpo è il tuo alleato più fedele.",
  "Il movimento è la lingua universale del benessere.",
  "Stai costruendo una salute che si vede anche negli occhi.",
  "La cura del corpo è cura dell'anima.",
  "Ogni sessione è un'opportunità per conoscerti meglio.",
  "Stai imparando a vivere in un corpo forte e presente.",
  "Il movimento quotidiano è una dichiarazione di amor proprio.",
  "Stai costruendo un capitale di salute per gli anni futuri.",
  "La fatica di oggi è l'energia di domani.",
  "Ogni sessione illumina la giornata intera.",
  "Stai imparando a trovare gioia nell'impegno fisico.",
  "Il corpo prospera con amore e movimento.",
  "Ogni rep rafforza il legame tra mente e corpo.",
  "Stai costruendo disciplina con dolcezza.",
  "La tua forza è reale, anche se non la vedi ancora.",
  "Ogni sessione è un rituale di benessere personale.",
  "Stai imparando a essere grato per il corpo che hai.",
  "Il movimento è la risposta a molte domande della vita.",
  "Ogni rep è un piccolo trionfo personale.",
  "Stai costruendo la tua migliore versione con pazienza.",
  "La costanza è il ponte tra i sogni e i risultati.",
  "Ogni sessione ti avvicina alla vita che vuoi vivere.",
  "Stai imparando che il corpo ama essere sfidato con rispetto.",
  "Il benessere fisico è il fondamento di tutto.",
  "Ogni rep è un gesto di fiducia verso te stesso.",
  "Stai costruendo un corpo che lavora per te.",
  "La tua salute è il tuo bene più prezioso.",
  "Ogni sessione aggiunge chiarezza alla tua mente.",
  "Stai imparando a muoverti con consapevolezza.",
  "Il corpo risponde con gratitudine a ogni sforzo sincero.",
  "Ogni rep costruisce un legame più forte con te stesso.",
  "Stai scoprendo quanto sei capace davvero.",
  "La semplicità del movimento nasconde una grande potenza.",
  "Ogni sessione è un momento solo tuo.",
  "Stai costruendo la versione di te che vuoi essere.",
  "Il tuo corpo è uno strumento meraviglioso, suonalo bene.",
  "Ogni rep è un passo in avanti nella vita che desideri.",
  "Stai imparando che la continuità è la vera forza.",
  "Il movimento regolare è la routine più potente che esista.",
  "Ogni sessione rafforza la tua identità di persona attiva.",
  "Stai costruendo salute con ogni singola rep.",
  "La tua dedizione di oggi è il tuo benessere di domani.",
  "Ogni respiro durante lo sforzo è prezioso.",
  "Stai imparando a valorizzare ciò che il tuo corpo fa per te.",
  "Il movimento è un atto di gratitudine verso la vita.",
  "Ogni rep ti rende più consapevole della tua forza.",
  "Stai costruendo una storia personale di cui andare fiero.",
  "La calma interiore si costruisce anche qui, con la fatica.",
  "Ogni sessione è un investimento in te stesso.",
  "Stai imparando che ogni giorno è un'occasione per crescere.",
  "Il corpo ama sentirsi usato con rispetto e intenzione.",
  "Ogni rep rafforza la tua capacità di affrontare le sfide.",
  "Stai costruendo una vitalità che permea tutta la tua vita.",
  "La tua forza cresce in silenzio, ma cresce.",
  "Ogni sessione è una risposta affermativa alla vita.",
  "Stai imparando che il benessere è una pratica, non un risultato.",
  "Il movimento quotidiano è il fondamento di una vita piena.",
  "Ogni rep è una promessa che mantieni a te stesso.",
  "Stai costruendo fiducia nel tuo corpo e nelle tue capacità.",
  "La semplicità del muoversi ogni giorno è rivoluzionaria.",
  "Ogni sessione è un momento in cui scegli te stesso.",
  "Stai imparando che prendersi cura di sé è un atto coraggioso.",
  "Il corpo ti sorprenderà con ciò che riesce a fare.",
  "Ogni rep è parte di un disegno più grande: la tua salute.",
  "Stai costruendo un rituale di cura che cambierà tutto.",
  "La tua capacità di muoverti è un dono, valorizzala.",
  "Ogni sessione costruisce il terreno su cui fiorisce la tua vita.",
  "Stai imparando che il rispetto del proprio corpo è essenziale.",
  "Il movimento intenzionale è la forma più alta di autocura.",
  "Ogni rep è un passo verso una vita più consapevole.",
  "Stai costruendo un'identità di forza e stabilità.",
  "La tua coerenza è la tua più grande realizzazione.",
  "Ogni sessione è un 'sì' alla vita che vuoi costruire.",
  "Stai imparando che la fatica conduce alla chiarezza.",
  "Il corpo che alleni diventa il corpo di cui ti fidi.",
  "Ogni rep è un atto di rispetto verso ciò che puoi diventare.",
  "Stai costruendo una vita più energica e presente.",
  "La tua pratica quotidiana è la cosa più importante che fai.",
  "Ogni sessione porta serenità nella vita fuori dalla palestra.",
  "Stai imparando che il movimento è gioia in forma fisica.",
  "Il corpo forte è la base di una mente serena.",
  "Ogni rep ti avvicina alla versione di te che ammiri.",
  "Stai costruendo forza con la stessa cura di un artigiano.",
  "La tua scelta di muoverti ogni giorno è straordinaria.",
  "Ogni sessione è un tassello nel mosaico del tuo benessere.",
  "Stai imparando che il corpo è un dono da rispettare.",
  "Il movimento regolare porta pace e chiarezza.",
  "Ogni rep è parte del tuo cammino verso il meglio.",
  "Stai costruendo abitudini che ti porteranno lontano.",
  "La tua forza interiore si manifesta attraverso il movimento.",
  "Ogni sessione è un dialogo profondo con te stesso.",
  "Stai imparando a muoverti con gratitudine.",
  "Il corpo ringrazia ogni volta che lo porti a muoversi.",
  "Ogni rep è un mattone nella costruzione della tua salute.",
  "Stai costruendo una base solida per una vita piena.",
  "La tua dedizione quotidiana è un atto di saggezza.",
  "Ogni sessione è un passo verso la versione più sana di te.",
  "Stai imparando che la cura del corpo è cura della vita.",
  "Il movimento ti rende più presente in ogni momento.",
  "Ogni rep costruisce il tuo futuro, una alla volta.",
  "Stai costruendo una versione di te che non ha paura di niente.",
  "La tua pratica è il tuo superpotere.",
  "Ogni sessione lascia il tuo corpo più capace di ieri.",
  "Stai imparando che la disciplina è una forma di libertà.",
  "Il corpo fiorisce quando riceve attenzione e movimento.",
  "Ogni rep è una pietra nel sentiero verso la tua salute.",
  "Stai costruendo qualcosa di cui essere fiero ogni giorno.",
  "La tua presenza costante è il messaggio più potente.",
  "Ogni sessione è una firma sulla tua dedizione.",
  "Stai imparando che prendersi cura di sé non è egoismo.",
  "Il movimento regolare è il segreto di chi vive bene.",
  "Ogni rep è un atto di fiducia nel processo.",
  "Stai costruendo un corpo che ti porta dove vuoi andare.",
  "La tua energia cresce ad ogni sessione che completi.",
  "Ogni sessione è un regalo che fai alla tua vita futura.",
  "Stai imparando che la forza vera è quella duratura.",
  "Il corpo riceve ogni sforzo e lo trasforma in capacità.",
  "Ogni rep è un contributo al tuo benessere globale.",
  "Stai costruendo la salute come si costruisce un'opera d'arte.",
  "La tua resilienza cresce ogni volta che non ti fermi.",
  "Ogni sessione è un capitolo nella storia del tuo benessere.",
  "Stai imparando che il corpo risponde sempre alla cura.",
  "Il movimento è la tua risposta più potente alla vita.",
  "Ogni rep porta luce in ogni parte della tua giornata.",
  "Stai costruendo un rapporto di fiducia con il tuo corpo.",
  "La tua costanza nel tempo vale più di qualsiasi intensità.",
  "Ogni sessione è un incontro tra chi sei e chi puoi essere.",
  "Stai imparando che il benessere si costruisce dal dentro.",
  "Il corpo ti appartiene e merita la tua attenzione.",
  "Ogni rep è un segnale di cura che mandi a te stesso.",
  "Stai costruendo vitalità, un allenamento alla volta.",
  "La tua pratica è un atto d'amore verso te stesso.",
  "Ogni sessione porta forza e chiarezza insieme.",
  "Stai imparando che il corpo è sempre dalla tua parte.",
  "Il movimento è il linguaggio più diretto della cura di sé.",
  "Ogni rep rafforza la tua capacità di essere presente.",
  "Stai costruendo il fondamento di ogni altro obiettivo.",
  "La tua salute è il tuo punto di partenza per tutto.",
  "Ogni sessione è una risposta positiva a ciò che sei.",
  "Stai imparando che ogni piccolo sforzo conta davvero.",
  "Il corpo cresce quando riceve attenzione gentile e continua.",
  "Ogni rep è parte di te che diventa sempre più forte.",
  "Stai costruendo una vita dove il movimento è gioia.",
  "La fatica che senti oggi si trasformerà in capacità domani.",
  "Ogni sessione è un passo verso la vita che immagini.",
  "Stai imparando che la forza si costruisce lentamente e bene.",
  "Il movimento ti dà qualcosa che nient'altro può darti.",
  "Ogni rep è un momento in cui sei pienamente presente.",
  "Stai costruendo una versione di te più sana e consapevole.",
  "La tua scelta di allenarti è una delle più sane che puoi fare.",
  "Ogni sessione è un contributo alla tua qualità della vita.",
  "Stai imparando che il corpo è un alleato, non un nemico.",
  "Il movimento costruisce ponti tra la mente e il corpo.",
  "Ogni rep è parte del racconto che stai scrivendo su di te.",
  "Stai costruendo la tua migliore storia, una sessione alla volta.",
  "La tua energia oggi è il tuo patrimonio di domani.",
  "Ogni sessione è la dimostrazione che hai scelto te.",
  "Stai imparando che l'amore per il proprio corpo si esprime qui.",
  "Il corpo fiorisce in un ambiente di rispetto e cura.",
  "Ogni rep è un atto di fede nel cambiamento.",
  "Stai costruendo un capitale di energia e benessere.",
  "La tua determinazione silenziosa è ammirevole.",
  "Ogni sessione è un momento in cui decidi il tuo futuro.",
  "Stai imparando che il movimento è uno strumento di pace.",
  "Il corpo lavora per te ogni volta che lo lasci lavorare.",
  "Ogni rep è una delle fondamenta della tua salute.",
  "Stai costruendo chiarezza mentale attraverso l'impegno fisico.",
  "La tua pratica è un pilastro della tua vita.",
  "Ogni sessione trasforma la fatica in crescita.",
  "Stai imparando che il benessere è una conquista quotidiana.",
  "Il movimento regolare è la chiave di volta della salute.",
  "Ogni rep è un momento di connessione autentica con te stesso.",
  "Stai costruendo forza interiore attraverso quella esteriore.",
  "La tua coerenza è il segnale più potente che puoi darti.",
  "Ogni sessione è un passo avanti verso chi vuoi essere.",
  "Stai imparando che il corpo risponde sempre al rispetto.",
  "Il movimento è la tua ancora nel presente.",
  "Ogni rep ti insegna qualcosa di nuovo su te stesso.",
  "Stai costruendo un futuro più sano e più sereno.",
  "La tua tenacia nel tornare è la tua virtù più bella.",
  "Ogni sessione nutre il corpo e calma la mente.",
  "Stai imparando che il corpo è uno strumento di conoscenza.",
  "Il movimento intenzionale porta con sé sempre un dono.",
  "Ogni rep è un capitolo della storia della tua salute.",
  "Stai costruendo un benessere che si irradierà in tutta la tua vita.",
  "La tua pratica è la migliore risposta ai ritmi frenetici del mondo.",
  "Ogni sessione è un momento di ritorno a ciò che conta.",
  "Stai imparando che la forza gentile è la più duratura.",
  "Il corpo che si muove è un corpo che ringrazia.",
  "Ogni rep è un momento di connessione con la tua forza.",
  "Stai costruendo una vita dove senti il tuo corpo come un alleato.",
  "La tua pratica quotidiana vale più di qualsiasi risultato istantaneo.",
  "Ogni sessione porta con sé il seme di qualcosa di grande.",
  "Stai imparando che il movimento è la medicina più naturale.",
  "Il corpo vuole muoversi, e tu glielo stai permettendo.",
  "Ogni rep è parte di un percorso che ha senso.",
  "Stai costruendo una fondazione su cui ogni cosa può crescere.",
  "La tua regolarità è la forma più alta di rispetto verso te stesso.",
  "Ogni sessione è un momento di connessione autentica con la vita.",
  "Stai imparando che la salute si costruisce rep per rep.",
  "Il corpo si apre e si rafforza con ogni sessione.",
  "Ogni rep conta e ha un valore che non si vede subito.",
  "Stai costruendo la versione di te che non si arrende.",
  "La tua presenza costante è il più grande dei risultati.",
  "Ogni sessione è un atto di cura verso il corpo che ti ospita.",
  "Stai imparando che il movimento è una forma di gratitudine.",
  "Il corpo cresce quando la mente lo accompagna con dolcezza.",
  "Ogni rep è parte di una trasformazione silenziosa ma reale.",
  "Stai costruendo una vita in movimento, una sessione alla volta.",
  "La tua dedizione è il seme da cui nasce tutto il resto.",
  "Ogni sessione aggiunge un nuovo strato alla tua forza.",
  "Stai imparando che prendersi cura di sé è un atto rivoluzionario.",
  "Il corpo sa riconoscere la cura e risponde con gratitudine.",
  "Ogni rep è il modo in cui dici 'sì' a te stesso.",
  "Stai costruendo la salute come un artigiano costruisce un'opera.",
  "La tua pratica è la cosa più concreta che fai per te.",
  "Ogni sessione è una risposta al desiderio di vivere bene.",
  "Stai imparando che il corpo è capace di incredibili adattamenti.",
  "Il movimento è il modo più diretto per sentirti vivo.",
  "Ogni rep è un piccolo passo in un viaggio meraviglioso.",
  "Stai costruendo qualcosa che nessuno può toglierti.",
  "La tua forza cresce silenziosamente ma inesorabilmente.",
  "Ogni sessione è una celebrazione di ciò che sei e puoi essere.",
  "Stai imparando a rispettare e valorizzare il tuo corpo.",
  "Il corpo ti chiede solo coerenza, e tu gliela stai dando.",
  "Ogni rep è un contributo al tuo progetto di vita.",
  "Stai costruendo la versione di te che vive pienamente.",
  "La tua pratica è un dialogo continuo con il tuo potenziale.",
  "Ogni sessione è un momento in cui il corpo e la mente si incontrano.",
  "Stai imparando che la forza nasce dall'interno e si manifesta fuori.",
  "Il movimento è il ponte tra ciò che sei e ciò che puoi essere.",
  "Ogni rep è un atto di presenza totale.",
  "Stai costruendo vitalità che permeera ogni aspetto della tua vita.",
  "La tua perseveranza silenziosa è la più potente di tutte.",
  "Ogni sessione è la tua risposta affermativa all'esistenza.",
  "Stai imparando che il corpo è saggio: ascoltalo mentre lo alleni.",
  "Il movimento quotidiano trasforma la vita in modo sottile ma profondo.",
  "Ogni rep è un momento in cui ti prendi sul serio.",
  "Stai costruendo la solidità su cui poggia tutto il resto della tua vita.",
  "La tua costanza è il linguaggio della fiducia verso te stesso.",
  "Ogni sessione è un confine che sposti un po' più in là.",
  "Stai imparando che il corpo vuole essere sfidato, con cura.",
  "Il movimento rivela la tua forza in modi che non ti aspetti.",
  "Ogni rep è parte di un ritmo che diventerà naturale.",
  "Stai costruendo un'identità che ha il movimento al suo centro.",
  "La tua pratica di oggi è il tuo punto di partenza di domani.",
  "Ogni sessione porta chiarezza e ordine nel resto della giornata.",
  "Stai imparando a muoverti con l'intenzione di chi si vuole bene.",
  "Il corpo si ricorda di ogni volta che gli hai dato attenzione.",
  "Ogni rep è un passo verso la vita che vuoi davvero.",
  "Stai costruendo una relazione di rispetto e fiducia con te stesso.",
  "La tua forza non è solo fisica: è anche mentale e spirituale.",
  "Ogni sessione è una finestra aperta sul tuo potenziale.",
  "Stai imparando che il benessere è fatto di gesti quotidiani e gentili.",
  "Il movimento ti ricorda chi sei davvero.",
  "Ogni rep è un momento di connessione con il tuo corpo.",
  "Stai costruendo la versione di te che vive con più energia.",
  "La tua pratica costante è un atto di fede nel tuo futuro.",
  "Ogni sessione è una risposta concreta ai tuoi obiettivi.",
  "Stai imparando che la salute è un viaggio, non una destinazione.",
  "Il corpo ti ringrazia per ogni volta che scegli di muoverti.",
  "Ogni rep è parte del rituale più importante della tua giornata.",
  "Stai costruendo un corpo che supporta ogni tua aspirazione.",
  "La tua dedizione quotidiana è la cosa più preziosa che possiedi.",
  "Ogni sessione è il modo in cui scegli di investire in te stesso.",
  "Stai imparando che il corpo e la mente crescono insieme.",
  "Il movimento è il più antico strumento di benessere che esiste.",
  "Ogni rep è la prova concreta del tuo impegno.",
  "Stai costruendo qualcosa di reale, di tangibile, di tuo.",
  "La tua pratica di muoverti regolarmente è la tua migliore decisione.",
  "Ogni sessione è un atto di presenza e cura verso ciò che sei.",
  "Stai imparando che il corpo risponde sempre con onestà.",
  "Il movimento ti aiuta a sentirti a casa dentro di te.",
  "Ogni rep è il modo più diretto per costruire il tuo benessere.",
  "Stai costruendo la tua migliore versione, con pazienza e amore.",
  "La tua costanza nel muoverti è il dono più grande che ti fai.",
  "Ogni sessione è un passo verso una vita più piena e consapevole.",
  "Stai imparando che la forza si costruisce con dolcezza e regolarità.",
  "Il corpo che alleni oggi sarà il corpo che ti porterà ovunque.",
  "Ogni rep è parte del mosaico del tuo benessere personale.",
  "Stai costruendo una vita dove la salute è la priorità.",
  "La tua pratica è un investimento che si moltiplica nel tempo.",
  "Ogni sessione è un momento sacro dedicato a te stesso.",
  "Stai imparando che il movimento è vita e la vita è movimento.",
  "Il corpo ama la cura costante e risponde con forza.",
  "Ogni rep è un tassello nel disegno del tuo benessere.",
  "Stai costruendo qualcosa che durerà molto più di oggi.",
  "La tua presenza costante all'allenamento è la tua firma personale.",
  "Ogni sessione è la conferma che scegli di voler stare bene.",
  "Stai imparando che ogni sforzo sincero porta i suoi frutti.",
  "Il movimento regolare è la fondazione di una vita fiorente.",
  "Ogni rep è un atto di rispetto verso il corpo che ti porta nel mondo.",
  "Stai costruendo la tua storia di benessere, una sessione alla volta.",
  "La tua forza aumenta ogni volta che mostri di credere in te.",
  "Ogni sessione è un ricordo che il tuo corpo custodirà.",
  "Stai imparando che il corpo è un alleato meraviglioso se lo rispetti.",
  "Il movimento è la tua risposta più concreta alla vita.",
  "Ogni rep aggiunge un mattone alla casa della tua salute.",
  "Stai costruendo la tua vita migliore, un allenamento alla volta.",
  "La tua pratica è la prova che ti vuoi davvero bene.",
  "Ogni sessione è il momento in cui smetti di aspettare e cominci.",
  "Stai imparando che la cura quotidiana è più potente di qualsiasi scatto.",
  "Il corpo si rafforza nell'intenzione e nella costanza.",
  "Ogni rep è una promessa mantenuta verso te stesso.",
  "Stai costruendo una versione di te più forte, più serena, più viva.",
  "La tua costanza è il messaggio più chiaro che puoi mandarti.",
  "Ogni sessione è la dimostrazione che puoi contare su te stesso.",
  "Stai imparando che il benessere è un atto d'amore quotidiano.",
  "Il movimento è il modo più bello di prendersi cura di sé.",
  "Ogni rep è una nota nella sinfonia del tuo benessere.",
  "Stai costruendo un futuro in cui ti senti bene nella tua pelle.",
  "La tua pratica quotidiana è il fondamento di tutto il resto.",
  "Ogni sessione è un inno alla vita che hai scelto di vivere.",
  "Stai imparando che il corpo vuole essere curato e lo dimostra.",
  "Il movimento ti radica nel presente e ti apre al futuro.",
  "Ogni rep è un gesto concreto verso la vita che vuoi.",
  "Stai costruendo salute, forza e consapevolezza insieme.",
  "La tua pratica è la tua ancora in un mondo che cambia.",
  "Ogni sessione è una dichiarazione silenziosa di chi sei.",
  "Stai imparando che la forza non si vede subito, ma si sente.",
  "Il corpo ti porta dove vuoi andare quando lo alleni con amore.",
  "Ogni rep è parte del tuo percorso verso il benessere pieno.",
  "Stai costruendo una vita in cui il corpo è un alleato gioioso.",
  "La tua dedizione è la forma più pura di rispetto verso te stesso.",
  "Ogni sessione è un passo nel tuo percorso di crescita personale.",
  "Stai imparando che il benessere fisico è il fondamento di tutto.",
  "Il movimento è la tua risposta alla fatica della vita quotidiana.",
  "Ogni rep ti rafforza dentro prima ancora che fuori.",
  "Stai costruendo forza con la pazienza di chi sa aspettare.",
  "La tua pratica è la tua migliore risposta alle sfide della vita.",
  "Ogni sessione è un incontro prezioso con te stesso.",
  "Stai imparando che il corpo è generoso con chi lo cura.",
  "Il movimento quotidiano è la tua scelta più coerente.",
  "Ogni rep è un pezzo di te che si rafforza e si rinnova.",
  "Stai costruendo la tua migliore versione, passo dopo passo.",
  "La tua forza è radicata nella regolarità, non nell'eccesso.",
  "Ogni sessione è una finestra aperta sulla tua forza latente.",
  "Stai imparando che muoversi è il modo più naturale per stare bene.",
  "Il corpo risponde con gioia a ogni cura che gli dedichi.",
  "Ogni rep è una nota in una melodia di salute e benessere.",
  "Stai costruendo un corpo che ti sostiene nella vita che scegli.",
  "La tua pratica costante è il tuo atto più sano.",
  "Ogni sessione è il momento in cui dai priorità a ciò che conta.",
  "Stai imparando che il movimento è la forma più concreta di autocura.",
  "Il corpo cresce nella costanza come le radici crescono nel tempo.",
  "Ogni rep è parte di una storia di forza che stai scrivendo.",
  "Stai costruendo un futuro in cui ti senti forte e libero.",
  "La tua scelta di allenarti regolarmente è una delle più sagge.",
  "Ogni sessione porta con sé un dono per il tuo corpo.",
  "Stai imparando che la disciplina amorevole è la più efficace.",
  "Il movimento ti connette a te stesso in modo unico.",
  "Ogni rep è parte del tessuto della tua vita sana.",
  "Stai costruendo la versione di te che vuole stare bene sempre.",
  "La tua pratica è il tuo punto fermo in una vita in movimento.",
  "Ogni sessione è un atto creativo verso la tua salute.",
  "Stai imparando che il corpo è capace di cose straordinarie.",
  "Il movimento regolare è la migliore risposta all'energia bloccata.",
  "Ogni rep ti avvicina alla pace interiore che cerchi.",
  "Stai costruendo un corpo e una mente che lavorano in armonia.",
  "La tua presenza costante è il regalo più grande che ti fai.",
  "Ogni sessione è un momento di connessione con la tua vitalità.",
  "Stai imparando che la salute si costruisce nei dettagli quotidiani.",
  "Il corpo ti parla attraverso la fatica: è un segno che sta crescendo.",
  "Ogni rep è un momento di lucidità e presenza.",
  "Stai costruendo la fondazione su cui si regge tutto il tuo benessere.",
  "La tua forza è già dentro di te, il movimento la libera.",
  "Ogni sessione è un passo concreto verso il tuo meglio.",
  "Stai imparando che muoversi è uno dei più grandi atti di libertà.",
  "Il corpo e la mente si nutrono dello stesso impegno.",
  "Ogni rep è un momento in cui decidi chi vuoi essere.",
  "Stai costruendo una vita in cui ti senti all'altezza di te stesso.",
  "La tua pratica quotidiana è il fondamento della tua fiducia.",
  "Ogni sessione è la tua firma sulla storia che stai scrivendo.",
  "Stai imparando che il corpo è il tuo compagno più fidato.",
  "Il movimento è il modo più naturale per sentirsi interi.",
  "Ogni rep porta con sé un beneficio che sentirai per anni.",
  "Stai costruendo la versione di te che non rimpiange nulla.",
  "La tua costanza è la più potente forma di amore verso te stesso.",
  "Ogni sessione è il momento in cui il tuo corpo fiorisce.",
  "Stai imparando che la forza vera nasce dalla gentilezza verso sé stessi.",
  "Il corpo si ricorda di ogni volta che lo hai scelto.",
  "Ogni rep è parte di un processo che ha il suo ritmo.",
  "Stai costruendo salute con lo stesso amore con cui costruiresti un'opera.",
  "La tua pratica è il modo più concreto di credere in te stesso.",
  "Ogni sessione è un regalo fatto alla versione futura di te.",
  "Stai imparando che ogni sforzo ha il suo posto nel percorso.",
  "Il movimento regolare è il segreto di chi vive a lungo e bene.",
  "Ogni rep è una dichiarazione: io valgo questo impegno.",
  "Stai costruendo un percorso di benessere che ti appartiene.",
  "La tua dedizione è il tuo patrimonio più prezioso.",
  "Ogni sessione è il momento in cui il futuro prende forma.",
  "Stai imparando che il corpo fiorisce quando è trattato con cura.",
  "Il movimento è il tuo linguaggio con te stesso.",
  "Ogni rep è parte di una trasformazione silenziosa e profonda.",
  "Stai costruendo la versione di te che è pronta per tutto.",
  "La tua pratica regolare è ciò che ti distingue.",
  "Ogni sessione è un investimento che si vede nel tempo.",
  "Stai imparando che la costanza è il più grande dei talenti.",
  "Il corpo vuole movimento come la mente vuole chiarezza.",
  "Ogni rep è un momento in cui scegli il tuo benessere.",
  "Stai costruendo forza, salute e fiducia in te stesso.",
  "La tua presenza qui oggi è la scelta più importante che hai fatto.",
  "Ogni sessione rafforza non solo il corpo, ma anche la volontà.",
  "Stai imparando che il benessere è una costruzione quotidiana.",
  "Il movimento è l'atto più antico di cura verso sé stessi.",
  "Ogni rep è un passo nel sentiero della tua salute.",
  "Stai costruendo un corpo forte e una mente serena.",
  "La tua pratica è la tua dichiarazione di amor proprio.",
  "Ogni sessione è un momento in cui il corpo dice grazie.",
];

export function getRandomFrase(): string {
  return frasiMotivazionali[Math.floor(Math.random() * frasiMotivazionali.length)];
}
